//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace Pi_Quartos.qmrservice {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://tempuri.org/")]
    public partial class Room : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int RoomIDField;
        
        private string RoomNameField;
        
        private bool OccupiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Occupied {
            get {
                return this.OccupiedField;
            }
            set {
                if ((this.OccupiedField.Equals(value) != true)) {
                    this.OccupiedField = value;
                    this.RaisePropertyChanged("Occupied");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="qmrservice.qmrserviceSoap")]
    public interface qmrserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoomByRoomID", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomByRoomIDResponse> GetRoomByRoomIDAsync(Pi_Quartos.qmrservice.GetRoomByRoomIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRoomBySensorID", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomBySensorIDResponse> GetRoomBySensorIDAsync(Pi_Quartos.qmrservice.GetRoomBySensorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetListRoomsResponse> GetListRoomsAsync(Pi_Quartos.qmrservice.GetListRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddRoomResponse> AddRoomAsync(Pi_Quartos.qmrservice.AddRoomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSensor", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddSensorResponse> AddSensorAsync(Pi_Quartos.qmrservice.AddSensorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveRoom", ReplyAction="*")]
        System.Threading.Tasks.Task ReserveRoomAsync(int roomID, bool occupied);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveRoomBySensor", ReplyAction="*")]
        System.Threading.Tasks.Task ReserveRoomBySensorAsync(int sensorID, int roomID, bool occupied);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.LoginResponse> LoginAsync(Pi_Quartos.qmrservice.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomByRoomIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomByRoomID", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetRoomByRoomIDRequestBody Body;
        
        public GetRoomByRoomIDRequest() {
        }
        
        public GetRoomByRoomIDRequest(Pi_Quartos.qmrservice.GetRoomByRoomIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomByRoomIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int value;
        
        public GetRoomByRoomIDRequestBody() {
        }
        
        public GetRoomByRoomIDRequestBody(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomByRoomIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomByRoomIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetRoomByRoomIDResponseBody Body;
        
        public GetRoomByRoomIDResponse() {
        }
        
        public GetRoomByRoomIDResponse(Pi_Quartos.qmrservice.GetRoomByRoomIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomByRoomIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Pi_Quartos.qmrservice.Room GetRoomByRoomIDResult;
        
        public GetRoomByRoomIDResponseBody() {
        }
        
        public GetRoomByRoomIDResponseBody(Pi_Quartos.qmrservice.Room GetRoomByRoomIDResult) {
            this.GetRoomByRoomIDResult = GetRoomByRoomIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomBySensorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomBySensorID", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetRoomBySensorIDRequestBody Body;
        
        public GetRoomBySensorIDRequest() {
        }
        
        public GetRoomBySensorIDRequest(Pi_Quartos.qmrservice.GetRoomBySensorIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomBySensorIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int value;
        
        public GetRoomBySensorIDRequestBody() {
        }
        
        public GetRoomBySensorIDRequestBody(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRoomBySensorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoomBySensorIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetRoomBySensorIDResponseBody Body;
        
        public GetRoomBySensorIDResponse() {
        }
        
        public GetRoomBySensorIDResponse(Pi_Quartos.qmrservice.GetRoomBySensorIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRoomBySensorIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Pi_Quartos.qmrservice.Room GetRoomBySensorIDResult;
        
        public GetRoomBySensorIDResponseBody() {
        }
        
        public GetRoomBySensorIDResponseBody(Pi_Quartos.qmrservice.Room GetRoomBySensorIDResult) {
            this.GetRoomBySensorIDResult = GetRoomBySensorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListRooms", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetListRoomsRequestBody Body;
        
        public GetListRoomsRequest() {
        }
        
        public GetListRoomsRequest(Pi_Quartos.qmrservice.GetListRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRoomsRequestBody {
        
        public GetListRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.GetListRoomsResponseBody Body;
        
        public GetListRoomsResponse() {
        }
        
        public GetListRoomsResponse(Pi_Quartos.qmrservice.GetListRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<Pi_Quartos.qmrservice.Room> GetListRoomsResult;
        
        public GetListRoomsResponseBody() {
        }
        
        public GetListRoomsResponseBody(System.Collections.ObjectModel.ObservableCollection<Pi_Quartos.qmrservice.Room> GetListRoomsResult) {
            this.GetListRoomsResult = GetListRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoom", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.AddRoomRequestBody Body;
        
        public AddRoomRequest() {
        }
        
        public AddRoomRequest(Pi_Quartos.qmrservice.AddRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string roomName;
        
        public AddRoomRequestBody() {
        }
        
        public AddRoomRequestBody(string roomName) {
            this.roomName = roomName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.AddRoomResponseBody Body;
        
        public AddRoomResponse() {
        }
        
        public AddRoomResponse(Pi_Quartos.qmrservice.AddRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddRoomResponseBody {
        
        public AddRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSensorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSensor", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.AddSensorRequestBody Body;
        
        public AddSensorRequest() {
        }
        
        public AddSensorRequest(Pi_Quartos.qmrservice.AddSensorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSensorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int roomID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ipaddr;
        
        public AddSensorRequestBody() {
        }
        
        public AddSensorRequestBody(int roomID, string ipaddr) {
            this.roomID = roomID;
            this.ipaddr = ipaddr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSensorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSensorResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.AddSensorResponseBody Body;
        
        public AddSensorResponse() {
        }
        
        public AddSensorResponse(Pi_Quartos.qmrservice.AddSensorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddSensorResponseBody {
        
        public AddSensorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Pi_Quartos.qmrservice.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Pi_Quartos.qmrservice.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Pi_Quartos.qmrservice.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface qmrserviceSoapChannel : Pi_Quartos.qmrservice.qmrserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class qmrserviceSoapClient : System.ServiceModel.ClientBase<Pi_Quartos.qmrservice.qmrserviceSoap>, Pi_Quartos.qmrservice.qmrserviceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public qmrserviceSoapClient() : 
                base(qmrserviceSoapClient.GetDefaultBinding(), qmrserviceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.qmrserviceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public qmrserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(qmrserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), qmrserviceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public qmrserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(qmrserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public qmrserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(qmrserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public qmrserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomByRoomIDResponse> Pi_Quartos.qmrservice.qmrserviceSoap.GetRoomByRoomIDAsync(Pi_Quartos.qmrservice.GetRoomByRoomIDRequest request) {
            return base.Channel.GetRoomByRoomIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomByRoomIDResponse> GetRoomByRoomIDAsync(int value) {
            Pi_Quartos.qmrservice.GetRoomByRoomIDRequest inValue = new Pi_Quartos.qmrservice.GetRoomByRoomIDRequest();
            inValue.Body = new Pi_Quartos.qmrservice.GetRoomByRoomIDRequestBody();
            inValue.Body.value = value;
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).GetRoomByRoomIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomBySensorIDResponse> Pi_Quartos.qmrservice.qmrserviceSoap.GetRoomBySensorIDAsync(Pi_Quartos.qmrservice.GetRoomBySensorIDRequest request) {
            return base.Channel.GetRoomBySensorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetRoomBySensorIDResponse> GetRoomBySensorIDAsync(int value) {
            Pi_Quartos.qmrservice.GetRoomBySensorIDRequest inValue = new Pi_Quartos.qmrservice.GetRoomBySensorIDRequest();
            inValue.Body = new Pi_Quartos.qmrservice.GetRoomBySensorIDRequestBody();
            inValue.Body.value = value;
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).GetRoomBySensorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetListRoomsResponse> Pi_Quartos.qmrservice.qmrserviceSoap.GetListRoomsAsync(Pi_Quartos.qmrservice.GetListRoomsRequest request) {
            return base.Channel.GetListRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.GetListRoomsResponse> GetListRoomsAsync() {
            Pi_Quartos.qmrservice.GetListRoomsRequest inValue = new Pi_Quartos.qmrservice.GetListRoomsRequest();
            inValue.Body = new Pi_Quartos.qmrservice.GetListRoomsRequestBody();
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).GetListRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddRoomResponse> Pi_Quartos.qmrservice.qmrserviceSoap.AddRoomAsync(Pi_Quartos.qmrservice.AddRoomRequest request) {
            return base.Channel.AddRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddRoomResponse> AddRoomAsync(string roomName) {
            Pi_Quartos.qmrservice.AddRoomRequest inValue = new Pi_Quartos.qmrservice.AddRoomRequest();
            inValue.Body = new Pi_Quartos.qmrservice.AddRoomRequestBody();
            inValue.Body.roomName = roomName;
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).AddRoomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddSensorResponse> Pi_Quartos.qmrservice.qmrserviceSoap.AddSensorAsync(Pi_Quartos.qmrservice.AddSensorRequest request) {
            return base.Channel.AddSensorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.AddSensorResponse> AddSensorAsync(int roomID, string ipaddr) {
            Pi_Quartos.qmrservice.AddSensorRequest inValue = new Pi_Quartos.qmrservice.AddSensorRequest();
            inValue.Body = new Pi_Quartos.qmrservice.AddSensorRequestBody();
            inValue.Body.roomID = roomID;
            inValue.Body.ipaddr = ipaddr;
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).AddSensorAsync(inValue);
        }
        
        public System.Threading.Tasks.Task ReserveRoomAsync(int roomID, bool occupied) {
            return base.Channel.ReserveRoomAsync(roomID, occupied);
        }
        
        public System.Threading.Tasks.Task ReserveRoomBySensorAsync(int sensorID, int roomID, bool occupied) {
            return base.Channel.ReserveRoomBySensorAsync(sensorID, roomID, occupied);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Pi_Quartos.qmrservice.LoginResponse> Pi_Quartos.qmrservice.qmrserviceSoap.LoginAsync(Pi_Quartos.qmrservice.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Pi_Quartos.qmrservice.LoginResponse> LoginAsync(string username, string password) {
            Pi_Quartos.qmrservice.LoginRequest inValue = new Pi_Quartos.qmrservice.LoginRequest();
            inValue.Body = new Pi_Quartos.qmrservice.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Pi_Quartos.qmrservice.qmrserviceSoap)(this)).LoginAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.qmrserviceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.qmrserviceSoap)) {
                return new System.ServiceModel.EndpointAddress("https://qmr.guttman.cuny.edu/qmr/qmrservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return qmrserviceSoapClient.GetBindingForEndpoint(EndpointConfiguration.qmrserviceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return qmrserviceSoapClient.GetEndpointAddress(EndpointConfiguration.qmrserviceSoap);
        }
        
        public enum EndpointConfiguration {
            
            qmrserviceSoap,
        }
    }
}
